config:
  send_anonymous_usage_stats: false
  use_colors: true
meltano:
  outputs:
    dev:
      account: it51758.ap-southeast-3.aws
      database: DATABROS_DATABASE
      password: CapstoneProjectDE3
      role: DAB_ROLE
      schema: DAB_SCHEMA
      threads: 1
      type: snowflake
      user: Ihsanr22
      warehouse: DAB_WAREHOUSE
  target: dev