default:
  outputs:
    dev:
      type: postgres
      host: localhost #atau pake postgres
      user: postgres
      pass: postgres
      dbname: ecommerce_db
      schema: public
  target: dev

# Profil Snowflake yang baru ditambahkan
snowflake_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: <your_snowflake_account>  # Misalnya 'xy12345'
      user: <your_username>
      password: <your_password>
      role: <your_role>
      warehouse: <your_warehouse>
      database: <your_database>
      schema: <your_schema>
      threads: 1
